source.. = src/
output.. = bin/
bin.includes = META-INF/,\
               .,\
               ref_lib/commons-collections4-4.4.jar,\
               ref_lib/commons-compress-1.26.1.jar,\
               ref_lib/jackson-annotations-2.13.4.jar,\
               ref_lib/jackson-core-2.13.4.jar,\
               ref_lib/jackson-databind-2.13.4.2.jar,\
               ref_lib/log4j-api-2.25.3.jar,\
               ref_lib/log4j-core-2.25.3.jar,\
               ref_lib/poi-5.5.1.jar,\
               ref_lib/poi-ooxml-5.5.1.jar,\
               ref_lib/xmlbeans-5.2.1.jar,\
               plugin.xml
